// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMTChampionshipAPI.Data;

#nullable disable

namespace SMTChampionshipAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104100745_CreateTeams")]
    partial class CreateTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SMTChampionshipAPI.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ArName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
